name: 💡 건의사항 제출
description: 규칙, 일정, 운영 방식 등에 대한 제안이 있다면 남겨주세요.
labels: [suggestion]
body:
  - type: textarea
    id: proposal
    attributes:
      label: 어떤 내용을 제안하시나요?
      description: 간단한 제안 배경과 이유를 함께 설명해주세요.
      placeholder: "예: 문제 선정에 대해 투표제를 제안합니다."
    validations:
      required: true
