members:
  - seat: 1
    name: "nOOne-is-hier"
    solved_handle: "kanadachocolate"
    github: "nOOne-is-hier"
  - seat: 2
    name: "SDGeo12"
    solved_handle: "sdgeo20"
    github: "SDGeo12"
  - seat: 3
    name: "jiyunee02"
    solved_handle: "jiyun301"
    github: "jiyunee02"
  - seat: 4
    name: "skala-changhyun"
    solved_handle: "gcgc09"
    github: "skala-changhyun"
  - seat: 5
    name: "seo-youngjae"
    solved_handle: "heaven707"
    github: "seo-youngjae"
  - seat: 6
    name: "JinYeopKang"
    solved_handle: "jyyj14587"
    github: "JinYeopKang"
